@startuml
left to right direction
skinparam packageStyle rectangle

actor Cliente
actor Contador
actor IA

rectangle "Sistema Contabilidade Ágil" {

  (Enviar arquivos) as Upload
  (Gerenciar clientes) as Clientes
  (Gerenciar documentos) as ManageDocs
  (Revisar lançamentos) as Review
  (Aprovar lançamentos) as Aprove
  (Corrigir lançamentos) as toCorrect
  (Realizar lançamentos contábeis) as Lançamentos
}

Cliente --> Upload
Contador --> Clientes
Contador --> ManageDocs
Contador --> Lançamentos
IA --> Lançamentos

ManageDocs --> Review
Review --> Aprove
Review --> toCorrect

Review <-- Lançamentos

@enduml
